<style type="text/css" media="all">
    .neptFloating {
        position: absolute;
        bottom: 40px;
        right: 40px;
    }

    .neptFloating .sapMBtnIcon {
        line-height: 3.75rem;
        font-size: 1.5rem;
    }

    .neptFloating .sapMBtnInner {
        height: 3.75rem;
        width: 3.75rem;
        border-radius: 1.875rem;
        border: none;
        background: #EBB043;
    }
</style>